authors:
  dphil:
    name: Phillip Delgyado
    description: Филипп Дельгядо
    avatar: https://avatars.githubusercontent.com/u/82216825
  oleg40a:
    name: Oleg Soroka
    description: Олег Сорока
    avatar: https://avatars.githubusercontent.com/u/1663840
  vfabr:
    name: Victor Fabrichenko
    description: Виктор Фабриченко
    avatar: https://avatars.githubusercontent.com/u/7291638
  vsharovatov:
    name: Viltaly Sharovatov
    description: Виталий Шароватов
    avatar: https://avatars.githubusercontent.com/u/1388600