authors:
  dphil:
    name: Phillip Delgyado
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/82216825
  oleg40a:
    name: Oleg Soroka
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/1663840
  vfabr:
    name: Victor Fabrichenko
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/7291638
  vsharovatov:
    name: Viltaly Sharovatov
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/1388600