site_name: Modern Software Development
site_url: https://www.modernsd.org
theme:
  name: material
plugins:
  - search
  - open-in-new-tab
# nav:
#   - 'Home': 'index.md'
#   - 'О нас': 'about.md'
#   - 'Контент': 'content/'
#     -
