site_name: Modern Software Development
site_url: https://www.modernsd.org/

theme:
  name: material
  # custom_dir: overrides
  # theme_dir: overrides
  language: ru
  logo: img/modern_agile_wheel_english.svg
  favicon: img/modern_agile_wheel_english.svg
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.tabs.link
    # - content.tooltips
    - header.autohide
    - navigation.expand
    # - navigation.footer
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.path
    # - navigation.prune
    - navigation.sections
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      # primary: deep purple
      primary: indigo
      # accent: blue
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/modernsd
      name: Modern Software Development

copyright: "Copyright &copy; 2016-2023 Modern Software Development"

plugins:
  # - meta
  - blog:
      enabled: true
      blog_dir: content
      blog_toc: true
      # post_dir: "{blog}/posts"
      post_url_format: "{slug}"
      post_url_max_categories: 10
      post_slugify_separator: "-"
      post_excerpt_max_authors: 10
      post_excerpt_max_categories: 10
      post_excerpt_separator: <!-- more -->
      post_readtime: false
      # post_readtime_words_per_minute: 265
      archive: true
      archive_name: Записи встреч
      archive_toc: true
      categories: true
      categories_name: Разделы
      categories_slugify_separator: "-"
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      categories_toc: true
      # categories_allowed:
      #   - Встречи
      #   - Дебаты
      #   - Прочее
      #   - Victor Fabrichenko
      #   - Vladimir Sharovatov
      #   - Oleg Soroka
      #   - Phillip Delgyado
      pagination: true
      pagination_per_page: 25
      pagination_keep_content: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_url_format: "{page}"
      authors: true
      authors_file: "{blog}/.authors.yml"
      # draft: false
      # draft_on_serve: true
      # draft_if_future_date: false
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - open-in-new-tab
  - search
  - tags:
      tags_file: content/tags.md

markdown_extensions:
  # - admonition
  - attr_list
  # - codehilite         # Syntax coloring for code blocks
  # - def_list           # Adds syntax for definition lists
  # - sane_lists         # Enables list items with multiple paragraphs
  - toc:               # Builds a table of contents 
      permalink: true  # Puts a "#" at the end of each header, which copies a link to that header when clicked
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


# nav:
#   - 'Home': 'index.md'
#   - 'Записи встреч': 'content/'
#   - 'Прочее': 'other/index.md'
#   - 'Наши партнеры': 'partners/index.md'
