site_name: Modern Software Development
site_url: https://www.modernsd.org/

theme:
  name: material
  custom_dir: overrides
  theme_dir: overrides
  language: ru
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.code.select
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    # - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/modernsd
      name: Modern Software Development

copyright: "Copyright &copy; 2016-2023 Modern Software Development"

plugins:
  - search
  - open-in-new-tab

nav:
  - 'Home': 'index.md'
  - 'Контент':
      # - 'content/index.md'
      - 'Записи регулярных встреч': content/meetings/index.md
      - 'Прочее': 'content/other/index.md'
  - 'Наши партнеры': 'partners/index.md'

# nav:
#   - 'Home': 'index.md'
#   - 'О нас': 'about.md'
#   - 'Контент':
#     - 'Регулярные встречи': 'content/meetings/'
#     - 'Прочее': 'content/other/'
